site_name: PDEArena
site_description: Documentation for PDEArena
repo_name: microsoft/pdearena
repo_url: https://github.com/microsoft/pdearena
edit_uri: edit/main/docs/
markdown_extensions:
  - attr_list
  - tables
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: "¤"
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
theme:
  name: material
  features:
    - content.code.annotate
  custom_dir: docs/overrides
  font:
    text: Lato
    code: Noto Sans Mono
  palette:
    primary: teal
    accent: teal
  icon:
    repo: fontawesome/brands/github
    logo: material/stadium
  favicon: assets/images/favicon.ico


extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - css/mkdocstrings.css

nav:
  - Home: "index.md"
  - Installation: "install.md"
  - Repo Map: "repomap.md"
  - Architectures: "architectures.md"
  - Model Zoo: "modelzoo.md"
  - Data:
      - Generation: "data.md"
      - Download: "datadownload.md"
  - Training PDE Surrogates: "train.md"
  - Usage Scenarios:
      - Beginner: "scenarios/beginner.md"
      - Application: "scenarios/applied.md"
      - PDE Surrogate Research: "scenarios/researcher.md"
  - Research: "research.md"
  - Code Reference:
      - Data Loading: "reference/dataload.md"
      - Data Pipes: "reference/datapipes.md"
      - Architecture Modules: "reference/modules.md"
      - Conditioned Architecture Modules: "reference/condmodules.md"
      - Metrics: "reference/metrics.md"
      - Visualization: "reference/visualization.md"


plugins:
  - search
  - mkdocstrings:
      default_handler: python
      enable_inventory: true
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://pytorch.org/docs/stable/objects.inv
            - https://pytorch.org/data/beta/objects.inv
            - https://pytorch-lightning.readthedocs.io/en/stable/objects.inv
